/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.4. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module mfir2_6
    ( // Inputs
      input wire  clk // clock
    , input wire  rst // reset
    , input wire signed [7:0] x

      // Outputs
    , output wire signed [7:0] o
    );
  // Filters2_6.hs:19:1-87
  wire [47:0] c$ds_app_arg;
  // Filters2_6.hs:19:1-87
  reg [47:0] state = {8'sd0,   8'sd0,   8'sd0,   8'sd0,   8'sd0,   8'sd0};
  // Filters2_6.hs:19:1-87
  wire [47:0] newState1;
  // Filters2_6.hs:19:1-87
  wire [39:0] newState;
  wire [47:0] c$vec1;

  assign c$vec1 = {8'sd3,   8'sd5,   8'sd7,
                   8'sd11,   8'sd13,   8'sd17};

  // zipWith start
  genvar i;
  generate
  for (i = 0; i < 6; i = i + 1) begin : zipWith
    wire signed [7:0] zipWith_in1;
    assign zipWith_in1 = c$vec1[i*8+:8];
    wire signed [7:0] zipWith_in2;
    assign zipWith_in2 = newState1[i*8+:8];
    wire signed [7:0] c$n;
    assign c$n = zipWith_in1 * zipWith_in2;


    assign c$ds_app_arg[i*8+:8] = c$n;
  end
  endgenerate
  // zipWith end

  wire [47:0] vec;
  wire signed [7:0] acc_3_0;
  wire signed [7:0] acc_1;
  wire signed [7:0] acc_2;
  wire signed [7:0] acc_3;
  wire signed [7:0] acc_4;
  wire signed [7:0] acc_5;
  wire signed [7:0] acc_6;
  wire signed [7:0] acc_1_0;
  wire signed [7:0] acc_1_1;
  wire signed [7:0] acc_2_0;
  wire signed [7:0] acc_1_2;
  assign o = acc_3_0;

  assign vec = c$ds_app_arg;

  assign acc_1 = $signed(vec[47:40]);

  assign acc_2 = $signed(vec[39:32]);

  assign acc_3 = $signed(vec[31:24]);

  assign acc_4 = $signed(vec[23:16]);

  assign acc_5 = $signed(vec[15:8]);

  assign acc_6 = $signed(vec[7:0]);

  assign acc_1_0 = acc_1 + acc_2;



  assign acc_1_1 = acc_3 + acc_4;



  assign acc_1_2 = acc_5 + acc_6;



  assign acc_2_0 = acc_1_0 + acc_1_1;



  assign acc_3_0 = acc_2_0 + acc_1_2;





  // register begin
  always @(posedge clk or  posedge  rst) begin : state_register
    if ( rst) begin
      state <= {8'sd0,   8'sd0,   8'sd0,   8'sd0,   8'sd0,   8'sd0};
    end else begin
      state <= newState1;
    end
  end
  // register end

  assign newState1 = {x,   newState};

  assign newState = state[48-1 : 8];


endmodule

