/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.4. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module miir2
    ( // Inputs
      input wire  clk // clock
    , input wire  rst // reset
    , input wire signed [17:0] x

      // Outputs
    , output wire signed [17:0] o
    );
  // Filters4t_4_3.hs:(40,1)-(42,29)
  reg [179:0] c$ds_app_arg = {{18'sd8071,   -18'sd4857,   18'sd892},   {18'sd510,   18'sd1531,   18'sd1531,
                                           18'sd510},   {18'sd0,   18'sd0,
                                                         18'sd0}};
  wire [71:0] c$app_arg;
  // Filters4t_4_3.hs:29:1-4
  wire [71:0] bs;
  wire signed [17:0] result;
  wire signed [17:0] c$case_alt;
  wire [17:0] \r' ;
  wire [18:0] \c$r'_app_arg ;
  wire signed [18:0] r;
  // Filters4t_4_3.hs:29:1-4
  wire signed [17:0] c$inputSum_app_arg;
  // Filters4t_4_3.hs:29:1-4
  wire [53:0] c$inputSum_app_arg_0;
  // Filters4t_4_3.hs:29:1-4
  wire [53:0] regs;
  // Filters4t_4_3.hs:29:1-4
  wire [53:0] as;
  wire [71:0] c$vec2;
  wire [17:0] c$bv_10;
  wire [17:0] c$bv_11;
  wire [17:0] c$bv_12;
  wire [18:0] \r'_projection_2 ;

  // register begin
  always @(posedge clk or  posedge  rst) begin : c$ds_app_arg_register
    if ( rst) begin
      c$ds_app_arg <= {{18'sd8071,   -18'sd4857,   18'sd892},   {18'sd510,   18'sd1531,   18'sd1531,
                                             18'sd510},   {18'sd0,   18'sd0,
                                                           18'sd0}};
    end else begin
      c$ds_app_arg <= {as,   bs,   {result,(regs[54-1 : 18])}};
    end
  end
  // register end

  wire [71:0] vec;
  wire signed [17:0] acc_2_0;
  wire signed [17:0] acc_1;
  wire signed [17:0] acc_2;
  wire signed [17:0] acc_3;
  wire signed [17:0] acc_4;
  wire signed [17:0] acc_1_0;
  wire signed [17:0] acc_1_1;
  assign o = acc_2_0;

  assign vec = c$app_arg;

  assign acc_1 = $signed(vec[71:54]);

  assign acc_2 = $signed(vec[53:36]);

  assign acc_3 = $signed(vec[35:18]);

  assign acc_4 = $signed(vec[17:0]);

  wire signed [17:0] result_0;
  wire signed [17:0] c$case_alt_0;
  wire [17:0] \r'_0 ;
  wire [18:0] \c$r'_app_arg_0 ;
  wire signed [18:0] r_0;
  wire [17:0] c$bv;
  wire [17:0] c$bv_0;
  wire [17:0] c$bv_1;
  wire [18:0] \r'_projection ;
  assign acc_1_0 = result_0;

  assign c$bv = (\r'_0 );

  assign result_0 = ((( \c$r'_app_arg_0 [19-1] ) ^ ( c$bv[18-1] )) == 1'b0) ? ($signed(\r'_0 )) : c$case_alt_0;

  assign c$bv_0 = (($unsigned(acc_1)));

  assign c$bv_1 = (($unsigned(acc_2)));

  assign c$case_alt_0 = ((( c$bv_0[18-1] ) & ( c$bv_1[18-1] )) == 1'b0) ? 18'sd131071 : -18'sd131072;

  assign \r'_projection  = \c$r'_app_arg_0 ;

  assign \r'_0  = \r'_projection [17:0];

  assign \c$r'_app_arg_0  = ($unsigned(r_0));

  assign r_0 = acc_1 + acc_2;



  wire signed [17:0] result_1;
  wire signed [17:0] c$case_alt_1;
  wire [17:0] \r'_1 ;
  wire [18:0] \c$r'_app_arg_1 ;
  wire signed [18:0] r_1;
  wire [17:0] c$bv_2;
  wire [17:0] c$bv_3;
  wire [17:0] c$bv_4;
  wire [18:0] \r'_projection_0 ;
  assign acc_1_1 = result_1;

  assign c$bv_2 = (\r'_1 );

  assign result_1 = ((( \c$r'_app_arg_1 [19-1] ) ^ ( c$bv_2[18-1] )) == 1'b0) ? ($signed(\r'_1 )) : c$case_alt_1;

  assign c$bv_3 = (($unsigned(acc_3)));

  assign c$bv_4 = (($unsigned(acc_4)));

  assign c$case_alt_1 = ((( c$bv_3[18-1] ) & ( c$bv_4[18-1] )) == 1'b0) ? 18'sd131071 : -18'sd131072;

  assign \r'_projection_0  = \c$r'_app_arg_1 ;

  assign \r'_1  = \r'_projection_0 [17:0];

  assign \c$r'_app_arg_1  = ($unsigned(r_1));

  assign r_1 = acc_3 + acc_4;



  wire signed [17:0] result_2;
  wire signed [17:0] c$case_alt_2;
  wire [17:0] \r'_2 ;
  wire [18:0] \c$r'_app_arg_2 ;
  wire signed [18:0] r_2;
  wire [17:0] c$bv_5;
  wire [17:0] c$bv_6;
  wire [17:0] c$bv_7;
  wire [18:0] \r'_projection_1 ;
  assign acc_2_0 = result_2;

  assign c$bv_5 = (\r'_2 );

  assign result_2 = ((( \c$r'_app_arg_2 [19-1] ) ^ ( c$bv_5[18-1] )) == 1'b0) ? ($signed(\r'_2 )) : c$case_alt_2;

  assign c$bv_6 = (($unsigned(acc_1_0)));

  assign c$bv_7 = (($unsigned(acc_1_1)));

  assign c$case_alt_2 = ((( c$bv_6[18-1] ) & ( c$bv_7[18-1] )) == 1'b0) ? 18'sd131071 : -18'sd131072;

  assign \r'_projection_1  = \c$r'_app_arg_2 ;

  assign \r'_2  = \r'_projection_1 [17:0];

  assign \c$r'_app_arg_2  = ($unsigned(r_2));

  assign r_2 = acc_1_0 + acc_1_1;





  assign c$vec2 = ({result,regs});

  // zipWith start
  genvar i;
  generate
  for (i = 0; i < 4; i = i + 1) begin : zipWith
    wire signed [17:0] zipWith_in1;
    assign zipWith_in1 = bs[i*18+:18];
    wire signed [17:0] zipWith_in2;
    assign zipWith_in2 = c$vec2[i*18+:18];
    wire signed [17:0] c$n;
    wire signed [17:0] result_3;
    wire signed [17:0] c$case_alt_3;
    wire [5:0] c$app_arg_0;
    wire [4:0] c$app_arg_1;
    wire [4:0] rL;
    wire [30:0] rR;
    wire [35:0] ds3;
    wire signed [35:0] c$ds3_app_arg;
    wire [30:0] c$bv_8;
    wire [30:0] c$bv_9;
    assign c$n = result_3;

    assign c$bv_8 = (rR >> (64'sd13));

    assign result_3 = (((~ (| (c$app_arg_0))) | (& (c$app_arg_0))) == 1'b1) ? ($signed((c$bv_8[0+:18]))) : c$case_alt_3;

    assign c$case_alt_3 = (( c$app_arg_1[5-1] ) == 1'b0) ? 18'sd131071 : -18'sd131072;

    assign c$bv_9 = (rR);

    assign c$app_arg_0 = ({((( c$bv_9[31-1] ))),c$app_arg_1});

    assign c$app_arg_1 = rL;

    assign rL = ds3[35:31];

    assign rR = ds3[30:0];

    assign ds3 = (($unsigned(c$ds3_app_arg)));

    assign c$ds3_app_arg = zipWith_in1 * zipWith_in2;


    assign c$app_arg[i*18+:18] = c$n;
  end
  endgenerate
  // zipWith end

  assign bs = c$ds_app_arg[125:54];

  assign c$bv_10 = (\r' );

  assign result = ((( \c$r'_app_arg [19-1] ) ^ ( c$bv_10[18-1] )) == 1'b0) ? ($signed(\r' )) : c$case_alt;

  assign c$bv_11 = (($unsigned(c$inputSum_app_arg)));

  assign c$bv_12 = (($unsigned(x)));

  assign c$case_alt = ((( c$bv_11[18-1] ) & ( c$bv_12[18-1] )) == 1'b0) ? 18'sd131071 : -18'sd131072;

  assign \r'_projection_2  = \c$r'_app_arg ;

  assign \r'  = \r'_projection_2 [17:0];

  assign \c$r'_app_arg  = ($unsigned(r));

  assign r = c$inputSum_app_arg + x;

  wire [53:0] vec_0;
  wire signed [17:0] acc_2_0_1;
  wire signed [17:0] acc_0_3;
  wire signed [17:0] acc_0_4;
  wire signed [17:0] acc_1_0_0;
  wire signed [17:0] acc_0_5;
  assign c$inputSum_app_arg = acc_2_0_1;

  assign vec_0 = c$inputSum_app_arg_0;

  assign acc_0_3 = $signed(vec_0[53:36]);

  assign acc_0_4 = $signed(vec_0[35:18]);

  assign acc_0_5 = $signed(vec_0[17:0]);

  wire signed [17:0] result_7;
  wire signed [17:0] c$case_alt_7;
  wire [17:0] \r'_4 ;
  wire [18:0] \c$r'_app_arg_3 ;
  wire signed [18:0] r_3;
  wire [17:0] c$bv_13;
  wire [17:0] c$bv_14;
  wire [17:0] c$bv_15;
  wire [18:0] \r'_projection_3 ;
  assign acc_1_0_0 = result_7;

  assign c$bv_13 = (\r'_4 );

  assign result_7 = ((( \c$r'_app_arg_3 [19-1] ) ^ ( c$bv_13[18-1] )) == 1'b0) ? ($signed(\r'_4 )) : c$case_alt_7;

  assign c$bv_14 = (($unsigned(acc_0_3)));

  assign c$bv_15 = (($unsigned(acc_0_4)));

  assign c$case_alt_7 = ((( c$bv_14[18-1] ) & ( c$bv_15[18-1] )) == 1'b0) ? 18'sd131071 : -18'sd131072;

  assign \r'_projection_3  = \c$r'_app_arg_3 ;

  assign \r'_4  = \r'_projection_3 [17:0];

  assign \c$r'_app_arg_3  = ($unsigned(r_3));

  assign r_3 = acc_0_3 + acc_0_4;



  wire signed [17:0] result_8;
  wire signed [17:0] c$case_alt_8;
  wire [17:0] \r'_5 ;
  wire [18:0] \c$r'_app_arg_4 ;
  wire signed [18:0] r_4;
  wire [17:0] c$bv_16;
  wire [17:0] c$bv_17;
  wire [17:0] c$bv_18;
  wire [18:0] \r'_projection_4 ;
  assign acc_2_0_1 = result_8;

  assign c$bv_16 = (\r'_5 );

  assign result_8 = ((( \c$r'_app_arg_4 [19-1] ) ^ ( c$bv_16[18-1] )) == 1'b0) ? ($signed(\r'_5 )) : c$case_alt_8;

  assign c$bv_17 = (($unsigned(acc_1_0_0)));

  assign c$bv_18 = (($unsigned(acc_0_5)));

  assign c$case_alt_8 = ((( c$bv_17[18-1] ) & ( c$bv_18[18-1] )) == 1'b0) ? 18'sd131071 : -18'sd131072;

  assign \r'_projection_4  = \c$r'_app_arg_4 ;

  assign \r'_5  = \r'_projection_4 [17:0];

  assign \c$r'_app_arg_4  = ($unsigned(r_4));

  assign r_4 = acc_1_0_0 + acc_0_5;





  // zipWith start
  genvar i_0;
  generate
  for (i_0 = 0; i_0 < 3; i_0 = i_0 + 1) begin : zipWith_0
    wire signed [17:0] zipWith_in1_0;
    assign zipWith_in1_0 = as[i_0*18+:18];
    wire signed [17:0] zipWith_in2_0;
    assign zipWith_in2_0 = regs[i_0*18+:18];
    wire signed [17:0] c$n_0;
    wire signed [17:0] result_9;
    wire signed [17:0] c$case_alt_9;
    wire [5:0] c$app_arg_2;
    wire [4:0] c$app_arg_3;
    wire [4:0] rL_1;
    wire [30:0] rR_1;
    wire [35:0] ds3_0;
    wire signed [35:0] c$ds3_app_arg_0;
    wire [30:0] c$bv_19;
    wire [30:0] c$bv_20;
    assign c$n_0 = result_9;

    assign c$bv_19 = (rR_1 >> (64'sd13));

    assign result_9 = (((~ (| (c$app_arg_2))) | (& (c$app_arg_2))) == 1'b1) ? ($signed((c$bv_19[0+:18]))) : c$case_alt_9;

    assign c$case_alt_9 = (( c$app_arg_3[5-1] ) == 1'b0) ? 18'sd131071 : -18'sd131072;

    assign c$bv_20 = (rR_1);

    assign c$app_arg_2 = ({((( c$bv_20[31-1] ))),c$app_arg_3});

    assign c$app_arg_3 = rL_1;

    assign rL_1 = ds3_0[35:31];

    assign rR_1 = ds3_0[30:0];

    assign ds3_0 = (($unsigned(c$ds3_app_arg_0)));

    assign c$ds3_app_arg_0 = zipWith_in1_0 * zipWith_in2_0;


    assign c$inputSum_app_arg_0[i_0*18+:18] = c$n_0;
  end
  endgenerate
  // zipWith end

  assign regs = c$ds_app_arg[53:0];

  assign as = c$ds_app_arg[179:126];


endmodule

