/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.4. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module mfir3_6
    ( // Inputs
      input wire  clk // clock
    , input wire  rst // reset
    , input wire signed [7:0] x

      // Outputs
    , output wire signed [7:0] o
    );
  // Filters3_6.hs:24:1-4
  wire [39:0] scrut;
  // Filters3_6.hs:24:1-4
  wire [31:0] scrut1;
  // Filters3_6.hs:24:1-4
  wire [23:0] scrut2;
  // Filters3_6.hs:24:1-4
  wire [15:0] scrut3;
  // Filters3_6.hs:24:1-4
  wire [7:0] scrut4;
  // Filters3_6.hs:38:1-87
  reg [47:0] state = {8'sd0,   8'sd0,   8'sd0,   8'sd0,   8'sd0,   8'sd0};
  // Filters3_6.hs:38:1-87
  wire [47:0] newState1;
  // Filters3_6.hs:38:1-87
  wire [39:0] newState;

  assign o = (((($signed(newState1[48-1 -: 8])) + ($signed(scrut4[8-1 -: 8]))) * 8'sd3) + ((($signed(scrut[40-1 -: 8])) + ($signed(scrut3[16-1 -: 8]))) * 8'sd5)) + ((($signed(scrut1[32-1 -: 8])) + ($signed(scrut2[24-1 -: 8]))) * 8'sd7);

  assign scrut = newState1[40-1 : 0];

  assign scrut1 = scrut[32-1 : 0];

  assign scrut2 = scrut1[24-1 : 0];

  assign scrut3 = scrut2[16-1 : 0];

  assign scrut4 = scrut3[8-1 : 0];

  // register begin
  always @(posedge clk or  posedge  rst) begin : state_register
    if ( rst) begin
      state <= {8'sd0,   8'sd0,   8'sd0,   8'sd0,   8'sd0,   8'sd0};
    end else begin
      state <= newState1;
    end
  end
  // register end

  assign newState1 = {x,   newState};

  assign newState = state[48-1 : 8];


endmodule

