/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.4. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module mfir3t_6
    ( // Inputs
      input wire  clk // clock
    , input wire  rst // reset
    , input wire signed [7:0] x

      // Outputs
    , output wire signed [7:0] o
    );
  // Filters3t_6.hs:28:1-88
  reg [47:0] c$ds_app_arg = {8'sd0,   8'sd0,   8'sd0,   8'sd0,   8'sd0,   8'sd0};
  // Filters3t_6.hs:17:1-7
  wire [23:0] prod;
  wire [39:0] c$app_arg;
  // Filters3t_6.hs:17:1-7
  wire [39:0] x1;
  wire signed [7:0] c$l_app_arg;
  wire signed [7:0] c$l_app_arg_0;
  wire [23:0] c$vec1;
  wire [23:0] c$vec2;
  wire [39:0] c$vec1_0;
  wire [23:0] c$vec;
  wire [7:0] c$vec_0;
  wire [15:0] c$vec_1;

  // register begin
  always @(posedge clk or  posedge  rst) begin : c$ds_app_arg_register
    if ( rst) begin
      c$ds_app_arg <= {8'sd0,   8'sd0,   8'sd0,   8'sd0,   8'sd0,   8'sd0};
    end else begin
      c$ds_app_arg <= ({c$app_arg,$signed(prod[24-1 -: 8])});
    end
  end
  // register end

  assign o = $signed(c$ds_app_arg[48-1 -: 8]);

  assign c$vec1 = {8'sd3,   8'sd5,   8'sd7};

  assign c$vec2 = ({3 {x}});

  // zipWith start
  genvar i;
  generate
  for (i = 0; i < 3; i = i + 1) begin : zipWith
    wire signed [7:0] zipWith_in1;
    assign zipWith_in1 = c$vec1[i*8+:8];
    wire signed [7:0] zipWith_in2;
    assign zipWith_in2 = c$vec2[i*8+:8];
    wire signed [7:0] c$n;
    assign c$n = zipWith_in1 * zipWith_in2;


    assign prod[i*8+:8] = c$n;
  end
  endgenerate
  // zipWith end

  assign c$vec1_0 = (c$ds_app_arg[40-1 : 0]);

  // zipWith start
  genvar i_0;
  generate
  for (i_0 = 0; i_0 < 5; i_0 = i_0 + 1) begin : zipWith_0
    wire signed [7:0] zipWith_in1_0;
    assign zipWith_in1_0 = c$vec1_0[i_0*8+:8];
    wire signed [7:0] zipWith_in2_0;
    assign zipWith_in2_0 = x1[i_0*8+:8];
    wire signed [7:0] c$n_0;
    assign c$n_0 = zipWith_in1_0 + zipWith_in2_0;


    assign c$app_arg[i_0*8+:8] = c$n_0;
  end
  endgenerate
  // zipWith end

  assign c$vec = {x,   x,   x};

  assign x1 = {8'sd3 * ($signed(c$vec[24-1 -: 8])),
               c$l_app_arg_0,   c$l_app_arg,   c$l_app_arg,
               c$l_app_arg_0};

  assign c$vec_0 = x;

  assign c$l_app_arg = 8'sd7 * ($signed(c$vec_0[8-1 -: 8]));

  assign c$vec_1 = {x,   x};

  assign c$l_app_arg_0 = 8'sd5 * ($signed(c$vec_1[16-1 -: 8]));


endmodule

